### PR TITLE
Refactor ExtraManifestsRefs to allow cluster-wide references

### PR DESCRIPTION
**Pull request by sakhoury**
Currently ExtraManfiestsRefs is of type LocalObjectReference which implies that the ExtraManifest ConfigMap must be in the same namespace as the SiteConfig. This PR allows the ExtraManifest ConfigMap to exist in other namespaces.

### CODE REVIEW

**Comment by carbonin** [comment]
Is this something we actually want?
Remember @jnpacker's security/tenancy concern regarding non-local namespace references.

What's the use case for allowing these to reference CMs in separate namespaces? Couldn't the extramanifests contain data that a user might want to keep out of the hands of others deploying clusters on the same hub?

**Comment by sakhoury** [comment]
> Is this something we actually want? Remember @jnpacker's security/tenancy concern regarding non-local namespace references.
> 
> What's the use case for allowing these to reference CMs in separate namespaces? Couldn't the extramanifests contain data that a user might want to keep out of the hands of others deploying clusters on the same hub?

This was requested by Brent Rowsell. I believe the use-case is to allow for common extra-manifests to be defined in a shared namespace and thus avoid having to duplicate them across deployments.

**Comment by sakhoury** [comment]
Closing pull-request. The request to allow extra-manifests to exist in other namespaces can be re-considered in the future.

**Pull request closed without merging**
